spring.application.name=User-services

jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

server.port=8080

app.gateway.url=http://api-gateway:8081

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=true

# Configuraci�n PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres_user:5432/user_DB
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.cache.type=redis
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#spring.cache.redis.cache-null-values=true

# Configuracion de Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#Aqui el correo -> spring.mail.username=correo
#Aqui la contrasena -> spring.mail.password=contrasena
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
